{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pm2-on-premise.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-others
  labels:
    app: {{ template "pm2-on-premise.name" . }}
    chart: {{ template "pm2-on-premise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ template "pm2-on-premise.prometheuscollector.fullname" $ }}
              servicePort: 8081
            path: /prometheusCollector
          - backend:
              serviceName: {{ template "pm2-on-premise.prometheusexporter.fullname" $ }}
              servicePort: 8082
            path: /prometheusExporter
          - backend:
              serviceName: {{ template "pm2-on-premise.zipkincollector.fullname" $ }}
              servicePort: 8083
            path: /zipkinCollector
  {{- end }}
{{- end }}
