apiVersion: v1
kind: Service
metadata:
  name: {{ template "pm2-on-premise.prometheuscollector.fullname" . }}
  labels:
    app: {{ template "pm2-on-premise.prometheuscollector.fullname" . }}
    chart: {{ template "pm2-on-premise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      port: 8081
  selector:
    app: {{ template "pm2-on-premise.prometheuscollector.fullname" . }}
    release: {{ .Release.Name }}
