apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app-res: {{ template "keymetrics-aio.fullname" . }}
    app: {{ template "keymetrics-aio.name" .}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "keymetrics-aio.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-res: {{ template "keymetrics-aio.fullname" . }}
      app: {{ template "keymetrics-aio.name" .}}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app-res: {{ template "keymetrics-aio.fullname" . }}
        app: {{ template "keymetrics-aio.name" .}}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        name: {{ template "keymetrics-aio.fullname" . }}
    spec:
      containers:
      - image: rohja/km-nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: KM_ELASTICSEARCH_HOST
          value: {{ if .Values.use_embedded_elasticsearch }}{{ .Release.Name }}-elasticsearch-master.{{ .Release.Namespace }}:9200{{ else }}{{ .Values.km_elasticsearch_host }}{{ end }}
        - name: KM_MONGO_URL
          value: mongodb://{{ if .Values.use_embedded_mongodb }}{{ .Release.Name }}-mongodb.{{ .Release.Namespace }}:27017{{ .Values.km_mognodb_dbname }}{{ else }}{{ .Values.km_mongodb_host }}{{ end }}/{{ .Values.km_mongodb_dbname }}
        - name: KM_REDIS_URL
          value: redis://{{ if .Values.use_embedded_redis }}{{ .Release.Name }}-redis.{{ .Release.Namespace }}:6379{{ else }}{{ .Values.km_redis_host }}{{ end }}
        - name: NODE_ENV
          value: dedicated
        - name: SMTP_HOST
          value: {{ .Values.km_smtp_host }}
        - name: SMTP_USER
          value: {{ .Values.km_smtp_user }}
        - name: SMTP_PASSWORD
          value: {{ .Values.km_smtp_pass }}
        - name: SMTP_SENDER
          value: {{ .Values.km_smtp_sender }}
        - name: KM_SITE_URL
          value: {{ .Values.km_public_dns }}
        - name: KM_DEDICATED_KEY
          value: {{ .Values.km_license }}
        image: keymetrics/km-api:dedicated
        imagePullPolicy: IfNotPresent
        name: km-api
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: keymetrics/km-front:latest
        imagePullPolicy: Always
        name: km-front
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretsName }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
