apiVersion: v1
kind: Service
metadata:
  labels:
    app-res: {{ template "keymetrics-aio.fullname" . }}
    app: {{ template "keymetrics-aio.name" .}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "keymetrics-aio.fullname" . }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app-res: {{ template "keymetrics-aio.fullname" . }}
    app: {{ template "keymetrics-aio.name" .}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  sessionAffinity: None
  type: LoadBalancer
